services:
  - type: web
    name: easyxpense-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app -c gunicorn.conf.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GUNICORN_WORKERS
        value: 2